---
stages:
  - dependencies
  - build

variables:
  SCCACHE_GCS_BUCKET: btm-build-cache
  SCCACHE_GCS_RW_MODE: READ_WRITE
  SCCACHE_GCS_KEY_PATH: /tmp/storage-key.json
  DOCKER_DRIVER: overlay2

before_script:
  - echo $GCS_STORAGE_KEY > $SCCACHE_GCS_KEY_PATH

dependencies:
  stage: dependencies
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
  allow_failure: true
  image: docker:stable
  only:
    refs:
      - master
  services:
    - docker:dind
  before_script:
    - set -- $CI_JOB_NAME
    - export DOCKER_HOST="${DOCKER_HOST:-tcp://localhost:2375/}"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/builder:latest || true
    - docker pull rustlang/rust:nightly || true
  script:
    - >
      docker build -f Dockerfile.builder
      --cache-from $CI_REGISTRY_IMAGE:latest
      --cache-from rustlang/rust:nightly
      --tag $CI_REGISTRY_IMAGE/builder:latest
    - docker push $CI_REGISTRY_IMAGE/builder:latest

build:
  stage: build
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
  image: $CI_REGISTRY_IMAGE/builder:latest
  script:
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo build --verbose --all
    - cargo test --verbose --all
