language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      rust: nightly
      os: osx
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=x86_64-pc-windows-gnu
      rust: nightly
cache: cargo
before_cache: |
  chmod -R a+r $HOME/.cargo
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
deploy:
  - provider: cargo
    on:
      tags: true
    token:
      secure: GyyE0E7JSs/GgAVOKDsRK25OZAJryw/NrwuTxahKhawhGmpgQUcfRczKfCtdtPG0zqDLHu9e70c494ToL/pIf+36v26ULRpMgAfVXqiiClWzG5oMV4WPvZlwuUZudGqYrqEsFdLXDoax6A/LKWzducEgTdbANbIC+iBzGMEIX0Mhw8MWtQ19wEQrG4YC+k4vnTSxPsUbej1JdtAQqpRXPrY8PYRKihpPWEgevcxryoKm56o3xeFTtrom5qyp26UcPY+om/Fy2CL32XpX8dvbyjFJJgduD+pCiULmAquCuO8glQ/22Cu3mTi5ExcQHMQGvQyRWhKXcq71AfHAIXRLiGyAdK/B6x/+pt0a20dgTljJjMMzBXyEuS+DbsEfzBp2Bgp4gR0zUlyriNHI2PFf+R1wZNEA9M/vv++7VkPA7N86a59gTiKb/LxwGWi3Wt7uNb4UsF5/HMXBaCGTA1upZCNdKhFDurdRhkthpxg+ysd1Fzl/eghpdjaynfd6uZIVCgo7ptmT3/25g9aYpePacx5nF2XbdpfBk8hHWz8qBNY61qjYg3Dl6r2jumik7DyFqUHg14jrtmmg5shm9h4Srn20tGY2DuX9BGLuYq/ghdeGD74TVnQovtr+fIbvQPJjNPiR4EtAgkwTJ0UiKW3ekj33QFOilRpc2Tk/p48Sx80=
  - provider: releases
    api_key:
      secure: LgGNZLDT6ndLqN8Pi4523lJOzU3E/VCGZTnTT4EhdhmbrrEUfguhg0SSKMiSUU7NqOo4Jh65wYI3qb4y3RWsLJU8J9FR4ky8Nnasqi9CPGgVA5C0bXdypvkoJhS/scP9ujNRf2wJCnRbad4KX1bCYBH6FBv2N10XZiVNhNf1djhMKKdxtTJeOOa7TrgtlTAWwYzg29rk1DtcmjIicP2gzOuKz/eK3uPyDgsstxJ4D/0QfpxiTetZaU+MAkW+xTYUZ0zUC0gNtTu45ZDE7CBWrWj7zV5iRpFbrYIhpMUAEtmPeA4T9NxuJDFLl8TUvVap4BNTNKhBrh14v/HgOnOHL3TLc1tflCvUqcDZm1b0Fm1PilfzD/f3bcE1cCool3ZFPpHXewB3V1ulvgOvUydLfFT69JyuPSBzMimCZyEhNky3cwPStH1Nzb1fuSCLMlSZgHEyKbZ3sd7qGr6K7UdgU0dtPw7Tysg9aEmHg2XOjc1ijf0BvVkdwna3WWVewZ4atRHO1GkNBm3ieMw8MxlVTRNAJ54l7jwlJBNEQCk7PK+eTXW5XeWVFJ4vMqR+DcC0GIHYEJfHS2aMPpZ8cviaO7b/v7hQ6ppz2Iy7cmu1NAld2myMKOw5e/oaw5D7yJiZt/0e8ew0AvrYFkHeEzHHM3s2vTWC5XdZtfheLWgGhJ8=
    file_glob: true
    file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
    on:
      tags: true
    skip_cleanup: true
addons:
  apt:
    packages:
      - libssl-dev
